### ISSUE TITLE
Ramps placed after ball falls off may be in triggered position

### ISSUE THREAD

**Issue by Sgeo** [ASquirrelsTail/tumble-together#8]
This is an invalid configuration, which would lead to a marble bouncing.
![image](https://user-images.githubusercontent.com/251161/149016813-47748e17-ef65-4974-9889-458d771a2728.png)

After triggering a ball, a user might try to fix it:

![image](https://user-images.githubusercontent.com/251161/149017050-32808286-4c8d-457b-9432-47f77edcacde.png)

The ramp in the path, placed after the improper run, is visually acting as though the marble is rolling over it.

**Comment by ASquirrelsTail** [comment]
Fixed, will push to Heroku in the middle of the night at the weekend.
